version: '3.8'
services:

  mariadb:
    image: mariadb:10.6.2
    container_name: "ubudehe_db"
    restart: always
    networks:
      - "ubudehe_network"
    ports:
      - "8049:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "ubudehe"
      MYSQL_USER: "root"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+02:00']
    volumes:
      - mariadb-data:/var/lib/mysql/

  ubdehemanager:
    image: ubudehe-manager:v1
    container_name: ubudehemanager
    environment:
      SERVER_PORT: "8084"
      DB_HOSTNAME: "mariadb"
      DB_PORT: "3306"
      DB_DATABASE: "ubudehe"
      DB_USER: "root"
      DB_PASS: "password"
    restart: on-failure
    networks:
      - "ubudehe_network"
    ports:
      - "8085:8084"
    depends_on:
      - "mariadb"

volumes:
  mariadb-data:
    external: true

networks:
  ubudehe_network:
    name: ubudehe_network